apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-external
spec:
  type: LoadBalancer
  selector:
    app: mysql
  ports:
    - name: tcp
      port: 3306
      targetPort: 3306