http:
  address:  0.0.0.0:8080
  workers:
    command: "php psr-worker.php"

static:
  enable:  true
  dir:   "public"
  forbid: [".php", ".htaccess"]

reload:
  interval: 1s
  patterns: [".php",".env",".htaccess",".js",".css",".scss",".png",".jpg",".svg"]
  services:
    http:
      dirs: [""]
      recursive: true